apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8s-app
  template:
    metadata:
      labels:
        app: jenkins-k8s-app
    spec:
      containers:
      - name: jenkins-k8s-app
        image: cprathap/jenkins-k8s-app:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-service
spec:
  type: NodePort
  selector:
    app: jenkins-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007

